language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - npm test
after_success: "npm run coverage"
#  after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"